name: olkon_test_work
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: 3.21.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed: ^2.5.2
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  bloc: ^9.0.0
  drift: 2.21.0
  sqlite3_flutter_libs: 0.5.24
  path_provider: ^2.1.5
  flutter_bloc: ^9.1.0
  rxdart: ^0.28.0
  json_serializable: ^6.8.0
  fresh_dio: ^0.4.3
  flutter_secure_storage: 9.2.4
  shared_preferences: ^2.3.3
  octopus: 0.0.8
  google_fonts: 6.2.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  intl: ^0.20.2
  nested: ^1.0.0
  provider: ^6.1.4
  

dev_dependencies:
  drift_dev: 2.21.0
  json_annotation: ^4.9.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
